import { DashboardData } from "./types"

export const dashboardMock: DashboardData = {
  overview: {
    location: "Nuwara Eliya, Sri Lanka",
    timestamp: "Mon, 01 December 2025 09:37 AM",
    weather: {
      temperature: "22",
      condition: "Partly Cloudy",
      high: "24",
      low: "16",
    },
    zone: "Strawberry House 01",
    area: "180 m²",
  },
  metrics: [
    {
      id: "plant-health",
      label: "Plant Health",
      value: "94",
      unit: "%",
      helper: "Your plants are thriving",
      status: "good",
      trend: "up",
    },
    {
      id: "wind",
      label: "Wind",
      value: "2",
      unit: "m/s",
      helper: "Airflow is stable",
      status: "good",
      trend: "steady",
    },
    {
      id: "temperature",
      label: "Temperature",
      value: "19",
      unit: "°C",
      helper: "Maintain 15°C to 20°C",
      status: "good",
      trend: "steady",
    },
    {
      id: "ph",
      label: "pH Level",
      value: "7.6",
      helper: "Add acidic compost",
      status: "warning",
      trend: "up",
    },
    {
      id: "humidity",
      label: "Humidity",
      value: "82",
      unit: "%",
      helper: "Ventilation is sufficient",
      status: "good",
      trend: "steady",
    },
    {
      id: "soil-moisture",
      label: "Soil Moisture",
      value: "65",
      unit: "%",
      helper: "Monitoring is required",
      status: "good",
      trend: "down",
    },
  ],
  devices: [
    {
      id: "SM201",
      name: "JLNew H10 Soil Moisture Sensor",
      type: "Sensor",
      status: "online",
    },
    {
      id: "WS004",
      name: "HC T200 Wind Sensor",
      type: "Sensor",
      status: "online",
    },
    {
      id: "TH011",
      name: "ACE Temperature & Humidity Sensor",
      type: "Sensor",
      status: "issue",
      note: "Signal issue since 08:02 AM",
    },
    {
      id: "CM042",
      name: "VG550 Camera",
      type: "Camera",
      status: "online",
    },
    {
      id: "PM225",
      name: "Sanity PH Meter",
      type: "Sensor",
      status: "online",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Watering",
      window: "07:00 AM - 07:30 AM",
      description: "Water plants with 1 inch of water",
      status: "complete",
    },
    {
      id: "task-2",
      title: "Fertilizing",
      window: "07:30 AM - 10:00 AM",
      description: "Apply organic fertilizer",
      status: "complete",
    },
    {
      id: "task-3",
      title: "Pest Inspection",
      window: "10:00 AM - 11:00 AM",
      description: "Check leaves for pests",
      status: "pending",
    },
    {
      id: "task-4",
      title: "Soil Aeration",
      window: "02:00 PM - 03:00 PM",
      description: "Loosen soil carefully",
      status: "pending",
    },
  ],
  sections: [
    {
      id: "section-1",
      label: "Section 1",
      crop: "Spinach",
      score: 95,
      status: "good",
    },
    {
      id: "section-2",
      label: "Section 2",
      crop: "Spinach",
      score: 98,
      status: "good",
    },
    {
      id: "section-3",
      label: "Section 3",
      crop: "Spinach",
      score: 74,
      status: "warning",
    },
    {
      id: "section-4",
      label: "Section 4",
      crop: "Spinach",
      score: 87,
      status: "good",
    },
    {
      id: "section-7",
      label: "Section 7",
      crop: "Spinach",
      score: 52,
      status: "critical",
    },
  ],
  alerts: {
    total: 3,
    critical: 1,
    open: 2,
  },
  camera: {
    id: "cam-1",
    label: "Camera 1",
    url: "/camera-placeholder.jpg",
    thumbnails: ["/camera-placeholder.jpg"],
  },
}
